# Create directories for the web application
mkdir -p apps/nftrek-web/src/{components,services,hooks,contexts,assets,utils}

# Create directories for the backend
mkdir -p packages/backend/src/{controllers,models,services,middleware}

# Create directories for shared resources
mkdir -p shared/src/{types,utils}

# Create placeholder .env files and package.json for each package
touch apps/nftrek-web/{.env,package.json} \
      packages/backend/{.env,package.json} \
      shared/package.json

# Create a placeholder MoonRepo workspace configuration file
touch workspace.yml

# Create a standard .gitignore file
cat > .gitignore <<EOF
# Dependency directories
node_modules/

# Configurations
*.env

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
jspm_packages

# TypeScript v1 declaration files
typings

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and *not* the Gatsby cache
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

# Stores VSCode versions used for testing VSCode extensions
.vscode-test

# yarn v2
.yarn/*
!.yarn/cache
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions
EOF

# Initialize an empty git repository if one does not exist already
git init

# Add all files to the repository
git add .

# Commit the files
git commit -m "Initialize NFTrek project structure"
